# Generated by Django 5.0.3 on 2024-03-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='acc_no',
            field=models.CharField(default=6882815870, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.IntegerField(default=656907),
        ),
    ]
