# Generated by Django 5.0.3 on 2024-03-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_otp_code_alter_transaction_receiver_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='id',
            new_name='transaction_id',
        ),
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.IntegerField(default=520290),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='acc_no',
            field=models.CharField(default=1168835279, max_length=10, unique=True),
        ),
    ]
