# Generated by Django 5.0.3 on 2024-03-05 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_rename_id_transaction_transaction_id_alter_otp_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.IntegerField(default=468424),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='acc_no',
            field=models.CharField(default=4545495666, max_length=10, unique=True),
        ),
    ]
