# Generated by Django 5.0.4 on 2024-04-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_otp_code_alter_userprofile_acc_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.IntegerField(default=184805),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='acc_no',
            field=models.CharField(default=6057349662, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pin',
            field=models.CharField(default=3213, max_length=4),
        ),
    ]
